[tool.poetry]
name = "manga-image-translator"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

packages = [{ include = "manga_translator" }]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
langcodes = "^3.3.0"
networkx = "^3.1"
torch = "^2.0.1"
torchvision = "^0.15.2"
torch-summary = "^1.4.5"
einops = "^0.6.1"
scikit-image = "^0.21.0"
opencv-python = "^4.8.0.76"
pyclipper = "^1.3.0.post5"
shapely = "^2.0.1"
requests = "^2.31.0"
oscrypto = "^1.3.0"
freetype-py = "^2.4.0"
googletrans = "4.0.0rc1"
aiohttp = "^3.8.5"
tqdm = "^4.66.1"
deepl = "^1.15.0"
imagehash = "^4.3.1"
kornia = "^0.7.0"
backports-cached-property = "^1.0.2"
huggingface-hub = "^0.17.1"
transformers = "^4.33.2"
py3langid = "^0.2.2"
sentencepiece = "^0.1.99"
editdistance = "^0.6.2"
numpy = "^1.26.0"
tensorboardx = "^2.6.2.2"
websockets = "^11.0.3"
protobuf = ">=3"
ctranslate2 = "^3.19.0"
colorama = "^0.4.6"
openai = "^0.28.0"
open-clip-torch = "^2.20.0"
safetensors = "^0.3.3"
pandas = "^2.1.0"
onnxruntime = "^1.15.1"
omegaconf = "^2.3.0"
python-dotenv = "^1.0.0"
nest-asyncio = "^1.5.8"
marshmallow = "^3.20.1"
cython = "^3.0.2"
aioshutil = "^1.3"
aiofiles = "^23.2.1"
arabic-reshaper = "^3.0.0"
pyhyphen = "^4.0.3"
pydensecrf = { git = "https://github.com/kodalli/pydensecrf.git" }

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"
pylint = "^2.17.5"


[tool.isort]
profile = 'black'
multi_line_output = 3
line_length = 100
py_version = 310


[tool.pylint]
disable = """
C,R,W,
c-extension-no-member
"""
additional-builtins = "display"
output-format = "colorized"
generated-members = ["torch.*", "cv2.*"]
